CREATE TABLE dbo.PROCESSO
	(
	id int NOT NULL IDENTITY (1, 1),
	numero varchar(50) NOT NULL,
	tipo int
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PROCESSO ADD CONSTRAINT
	PK_PROCESSO PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PROCESSO]  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO] FOREIGN KEY([TIPO])
REFERENCES [dbo].[TIPO_PROCESSO] ([id])
GO

ALTER TABLE [dbo].[PROCESSO] CHECK CONSTRAINT [FK_PROCESSO]
GO
	
INSERT INTO PROCESSO (numero, tipo) 
	VALUES('PROCESSO  A', 1)
INSERT INTO PROCESSO (numero, tipo) 
	VALUES('PROCESSO  AB', 2)
INSERT INTO PROCESSO (numero, tipo) 
	VALUES('PROCESSO C', 3)
INSERT INTO PROCESSO (numero, tipo) 
	VALUES('PROCESSO', 4)
GO
