CREATE TABLE dbo.RISCO
	(
	id int NOT NULL IDENTITY (1, 1),
	categoria varchar(50) NOT NULL,

	)  ON [PRIMARY]
GO
ALTER TABLE dbo.RISCO ADD CONSTRAINT
	PK_RISCO PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

	
INSERT INTO RISCO (categoria) 
	VALUES('R1 - BAIXO')
INSERT INTO RISCO (categoria) 
	VALUES('R2 - MEDIO')
INSERT INTO RISCO (categoria) 
	VALUES('R3 - ALTO')
INSERT INTO RISCO (categoria) 
	VALUES('R4 - MUITO ALTO')
GO
