CREATE TABLE dbo.RISCO
	(
	id int NOT NULL IDENTITY (1, 1),
	categoria varchar(50) NOT NULL,

	)  ON [PRIMARY]
GO
ALTER TABLE dbo.RISCO ADD CONSTRAINT
	PK_RISCO PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

	
INSERT INTO RISCO (categoria) 
	VALUES('RISCO A')
INSERT INTO RISCO (categoria) 
	VALUES('RISCO AB')
INSERT INTO RISCO (categoria) 
	VALUES('RISCO A3')
INSERT INTO RISCO (categoria) 
	VALUES('RISCO A4')
GO
