CREATE TABLE dbo.LOCALIDADE
	(
	id int NOT NULL IDENTITY (1, 1),descricao
	descricao varchar(50) NOT NULL,

	)  ON [PRIMARY]
GO
ALTER TABLE dbo.LOCALIDADE ADD CONSTRAINT
	PK_LOCALIDADE PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

	
INSERT INTO LOCALIDADE (descricao) 
	VALUES('LOCALIDADE A')
INSERT INTO LOCALIDADE (descricao) 
	VALUES('LOCALIDADE AB')
INSERT INTO LOCALIDADE (descricao) 
	VALUES('LOCALIDADE A3')
INSERT INTO LOCALIDADE (descricao) 
	VALUES('LOCALIDADE A4')
GO