CREATE TABLE dbo.LOCALIDADE
	(
	id int NOT NULL IDENTITY (1, 1),
	descricao varchar(50) NOT NULL,

	)  ON [PRIMARY]
GO
ALTER TABLE dbo.LOCALIDADE ADD CONSTRAINT
	PK_LOCALIDADE PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

	
INSERT INTO LOCALIDADE (descricao) 
	VALUES('IBURA DE BAIXO')
INSERT INTO LOCALIDADE (descricao) 
	VALUES('BEBERIBE')
INSERT INTO LOCALIDADE (descricao) 
	VALUES('MACAXEIRA')
INSERT INTO LOCALIDADE (descricao) 
	VALUES('IMBIRIBEIRA')
GO