CREATE TABLE dbo.SOLICITACAO
	(
	id int NOT NULL IDENTITY (1, 1),
	momento	varchar(20),
	descricao varchar(50) NOT NULL,
	endereco varchar(30),
	roteiro varchar(30),
	origem_chamado varchar(30),
	vitimas_fatais bit,
	vitimas bit,
	plantao bit,
	longitude decimal,
	latitude decimal,
	bairro int,
	localidade int,
	REGIONAL int,
	RPA int,
	microregiao int

	)  ON [PRIMARY]
GO
ALTER TABLE dbo.SOLICITACAO ADD CONSTRAINT
	PK_SOLICITACAO PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO


ALTER TABLE [dbo].[SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_REGIONAL] FOREIGN KEY([REGIONAL])
REFERENCES [dbo].[REGIONAL] ([id])
GO

ALTER TABLE [dbo].[SOLICITACAO] CHECK CONSTRAINT [FK_REGIONAL]
GO

ALTER TABLE [dbo].[SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_BAIRRO] FOREIGN KEY([BAIRRO])
REFERENCES [dbo].[BAIRRO] ([id])
GO

ALTER TABLE [dbo].[SOLICITACAO] CHECK CONSTRAINT [FK_BAIRRO]
GO

ALTER TABLE [dbo].[SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_MICROREGIAO] FOREIGN KEY([MICROREGIAO])
REFERENCES [dbo].[MICROREGIAO] ([id])
GO

ALTER TABLE [dbo].[SOLICITACAO] CHECK CONSTRAINT [FK_MICROREGIAO]
GO

ALTER TABLE [dbo].[SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO_SOL] FOREIGN KEY([PROCESSO])
REFERENCES [dbo].[PROCESSO] ([id])
GO

ALTER TABLE [dbo].[SOLICITACAO] CHECK CONSTRAINT [FK_PROCESSO_SOL]
GO

ALTER TABLE [dbo].[SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_RPA] FOREIGN KEY([RPA])
REFERENCES [dbo].[RPA] ([id])
GO

ALTER TABLE [dbo].[SOLICITACAO] CHECK CONSTRAINT [FK_RPA]
GO

ALTER TABLE [dbo].[SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_LOCALIDADE] FOREIGN KEY([LOCALIDADE])
REFERENCES [dbo].[LOCALIDADE] ([id])
GO

ALTER TABLE [dbo].[SOLICITACAO] CHECK CONSTRAINT [FK_LOCALIDADE]
GO

INSERT INTO SOLICITACAO (
	momento,
	descricao,
	endereco,
	roteiro,
	origem_chamado,
	vitimas_fatais,
	vitimas,
	plantao,
	longitude,
	latitude,
	bairro,
	localidade,
	REGIONAL,
	RPA,
	microregiao
	) 
	VALUES ('2012-06-18 10:34:09', 'descricao',  'RUA DAS FLORES', 'ROTEIRO A', 'Sem Origem', 1, 1, 1, 1.0, 1.0, 1, 1, 1, 1, 1)

