CREATE TABLE dbo.PROCESSO_SOLICITACAO
	(
	descricao varchar(50),
	processo int NOT NULL,
	solicitacao int NOT NULL
	)  ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO_SOLICITACAO_PROCESSO] FOREIGN KEY([PROCESSO])
REFERENCES [dbo].[PROCESSO] ([id])
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO] CHECK CONSTRAINT [FK_PROCESSO_SOLICITACAO_PROCESSO]
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO_SOLICITACAO_SOLICITACAO] FOREIGN KEY([SOLICITACAO])
REFERENCES [dbo].[SOLICITACAO] ([id])
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO] CHECK CONSTRAINT [FK_PROCESSO_SOLICITACAO_SOLICITACAO]
GO
	
INSERT INTO PROCESSO_SOLICITACAO (
	descricao, 
	processo, 
	solicitacao
	) 
	VALUES('Descricao', 1, 1)

GO