CREATE TABLE dbo.RPA
	(
	id int NOT NULL IDENTITY (1, 1),
	descricao varchar(50) NOT NULL,
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.RPA ADD CONSTRAINT
	PK_RPA PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

	
INSERT INTO RPA (descricao) 
	VALUES('3-NOROESTE')
INSERT INTO RPA (descricao) 
	VALUES('5-SUDOESTE')
INSERT INTO RPA (descricao) 
	VALUES('2-NORTE')
INSERT INTO RPA (descricao) 
	VALUES('Não Informado')
GO
