CREATE TABLE dbo.PROCESSO_LOCALIZACAO
	(
	id int NOT NULL IDENTITY (1, 1),
	descricao varchar(50) NOT NULL

	)  ON [PRIMARY]
GO
ALTER TABLE dbo.PROCESSO_LOCALIZACAO ADD CONSTRAINT
	PK_PROCESSO_LOCALIZACAO PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

	
INSERT INTO PROCESSO_LOCALIZACAO (descricao) 
	VALUES('SEDEC GERENCIA REGIONAL PLANICIE')
INSERT INTO PROCESSO_LOCALIZACAO (descricao) 
	VALUES('CODECIR - GERENCIA REGIONAL PLANA')
INSERT INTO PROCESSO_LOCALIZACAO (descricao) 
	VALUES('CODECIR - GERENCIA REGIONAL NORTE')
INSERT INTO PROCESSO_LOCALIZACAO (descricao) 
	VALUES('CODECIR - GERENCIA DE ANALISE DE RISCOS')
GO
