CREATE TABLE dbo.PROCESSO_SOLICITACAO
	(
	id int NOT NULL IDENTITY (1, 1),
	atividade varchar(50),
	processo int NOT NULL,
	solicitacao int NOT NULL
	)  ON [PRIMARY]
GO

ALTER TABLE dbo.PROCESSO_SOLICITACAO ADD CONSTRAINT
	PK_PROCESSO_SOLICITACAO PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO_SOLICITACAO_PROCESSO] FOREIGN KEY([PROCESSO])
REFERENCES [dbo].[PROCESSO] ([id])
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO] CHECK CONSTRAINT [FK_PROCESSO_SOLICITACAO_PROCESSO]
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO]  WITH CHECK ADD  CONSTRAINT [FK_PROCESSO_SOLICITACAO_SOLICITACAO] FOREIGN KEY([SOLICITACAO])
REFERENCES [dbo].[SOLICITACAO] ([id])
GO

ALTER TABLE [dbo].[PROCESSO_SOLICITACAO] CHECK CONSTRAINT [FK_PROCESSO_SOLICITACAO_SOLICITACAO]
GO
	
INSERT INTO PROCESSO_SOLICITACAO (
	atividade, 
	processo, 
	solicitacao
	) 
	VALUES('Atividade 01', 1, 1)

GO